//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.11 at 12:50:24 PM PST 
//


package io.spring.guides.accidents;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://spring.io/guides/accidents}accident"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accident"
})
@XmlRootElement(name = "AddAccidentResponse")
public class AddAccidentResponse {

    @XmlElement(required = true)
    protected Accident accident;

    /**
     * Gets the value of the accident property.
     * 
     * @return
     *     possible object is
     *     {@link Accident }
     *     
     */
    public Accident getAccident() {
        return accident;
    }

    /**
     * Sets the value of the accident property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accident }
     *     
     */
    public void setAccident(Accident value) {
        this.accident = value;
    }

}
