//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.11 at 12:50:24 PM PST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://spring.io/guides/accidents", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.spring.guides.accidents;
